angular.module("gmp.gmp-button", []).run(["$templateCache", function($templateCache) {$templateCache.put("gmp-button-template.html","<style type=\"text/css\">\n\n\n  /* Button\'s bottom bar */\n  .gmp-button-diag{\n    top: -70px;\n    left: -20px;\n    position: relative;\n    z-index: 0;\n    width: 200px;\n    height: 0px;\n    background-color: #2c3e50;\n    -webkit-transform: rotate(45deg);\n    -moz-transform: rotate(45deg);\n    transform: rotate(45deg);\n\n    -webkit-transition: height 300ms ease;\n    -moz-transition:    height 300ms ease;\n    -o-transition:      height 300ms ease;\n    transition:         height 300ms ease;\n    -webkit-transition-delay: 100ms;\n    -moz-transition-delay:    100ms;\n    -o-transition-delay:      100ms;\n    transition-delay:         100ms;\n  }\n\n  /* Button\'s text */\n  .gmp-button-text{\n    position: relative;\n    z-index: 10;\n  }\n\n\n  .gmp-button{\n    overflow: hidden;\n    font-family: \'Quicksand\', sans-serif;\n    text-align: center;\n    float: left;\n    margin-left: 10px;\n    /*vertical-align: middle;*/\n    width: 100px;\n    height: 51px;\n    color: white;\n    border: 1px solid #fff;\n    padding-top: 10px;\n    -webkit-transition: color 300ms ease;\n    -moz-transition:    color 300ms ease;\n    -o-transition:      color 300ms ease;\n    transition:         color 300ms ease;\n    /*padding-bottom: 10px;*/\n  }\n\n  .gmp-button-inside{\n    position: relative;\n    z-index: 1;\n    width: 0px;\n    height: 5px;\n    margin: 0 auto;\n    /*padding-top: 90px;*/\n    background: #fff;\n    margin-top: 10px;\n    -webkit-transition: width 300ms ease;\n    -moz-transition:    width 300ms ease;\n    -o-transition:      width 300ms ease;\n    transition:         width 300ms ease;\n  }\n\n\n  .gmp-button:hover{\n    color: pink;\n    /*background: rgba(22, 160, 133,1.0);*/\n  }\n\n  .gmp-button:hover > .gmp-button-inside{\n    width: 99px;\n  }\n\n  .gmp-button:hover > .gmp-button-diag{\n    height: 125px;\n  }\n\n</style>\n\n<div class=\"gmp-button\">\n  <div class=\"gmp-button-text\" ng-transclude></div>\n  <div class=\"gmp-button-inside\"></div>\n  <div class=\"gmp-button-diag\"></div>\n</div>\n");}])
  .directive('gmpButton', function($templateCache){
    return {
      restrict: 'E',
      transclude: true,
      scope: {},
      template: $templateCache.get("gmp-button-template.html"),
      link: function(scope, element){
      }
    };
  });;